[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["DATABASE_URL=file:./dev.db npx prisma generate && DATABASE_URL=file:./dev.db npx prisma migrate deploy && npx next build"]

[start]
cmd = "DATABASE_URL=file:./dev.db npx prisma migrate deploy && npx next start -H 0.0.0.0 -p ${PORT:-3000}"
